samuelskim1/5tack

backend/bin/www
backend/config/keys.js

connected mongoose

---

backend/app.js
backend/config/keys.js
backend/routes/api/csrf.js

finished express server security

finished express server security

---

backend/app.js
backend/config/keys.js
backend/routes/api/csrf.js

converted error handling into json responses instead of html

Expresserrorhandling

---

backend/models/User.js

complete userSchema

---

backend/validations/handleValidationErrors.js
backend/validations/login.js
backend/validations/register.js

create validations folder
- handlevalidationerrors to return errors if validations fail
- login and register validations

create validations for login and register in backend

---

backend/models/Comment.js
backend/models/User.js

finished comment schema

---

frontend/public/index.html
frontend/src/App.js
frontend/src/components/HomePage/HomePage.js
frontend/src/components/NavBar/NavBar.css
frontend/src/components/NavBar/NavBar.js
frontend/src/components/NavBar/UnauthNav.js
frontend/src/components/Routes/Routes.js
frontend/src/components/SplashPage/SplashPage.css
frontend/src/components/SplashPage/SplashPage.js
frontend/src/context/modal.css
frontend/src/context/modal.js
frontend/src/index.css
frontend/src/index.js
frontend/src/store/errors.js
frontend/src/store/jwt.js
frontend/src/store/session.js
frontend/src/store/store.js

- Set up frontend skeleton
- Start Navbar and Splash page components
- Set up JWT, session, and errors slice of state
- After merging: create login/signup form modals

Setupmainfrontenduath

---

backend/models/User.js

changed user model

---

backend/app.js
backend/routes/api/users.js

user registration done

---

backend/config/keys.js
backend/config/passport.js
backend/routes/api/users.js

passport jwt setup done

---

backend/config/passport.js
backend/routes/api/users.js

updated so that you can login in with username

updated username

---

backend/app.js
backend/routes/api/users.js

added a username route which shows the user by username and users/ route that shows all the users

added /username and / routes

---

backend/routes/api/users.js

added delete and update routes for user

added delete and update user

---

backend/app.js
backend/models/Post.js
backend/models/User.js
backend/package-lock.json
backend/package.json
backend/routes/api/posts.js
backend/routes/api/users.js
backend/seeders/seeds.js

finished posts routes

---

backend/config/passport.js
frontend/src/App.js
frontend/src/components/Profile/Profile.js
frontend/src/components/UserInfo/UserInfo.js
frontend/src/components/UserInfo/UserInfo.scss

create profile components, userinfo components, and add description and email to the userInfo object in passport.js in the backend

create profile and userinfo components

---

backend/models/User.js
backend/routes/api/users.js
backend/validations/updateUser.js
frontend/src/components/EditUserInfo/EditUserInfoForm.js
frontend/src/components/UserInfo/UserInfo.js
frontend/src/store/session.js

- create thunk action for updating users
- create validations for updating users
- creating edit user info form

create edit user info form and update thunk

---

backend/app.js
backend/models/Category.js
backend/models/Game.js
backend/routes/api/categories.js
backend/routes/api/posts.js

finished routes for categories

finished routes for categories

---

backend/app.js
backend/models/Category.js
backend/models/Game.js
backend/models/Post.js
backend/routes/api/categories.js
backend/routes/api/games.js

Gameroutes

---

backend/app.js
backend/models/Review.js
backend/routes/api/posts.js
backend/routes/api/reviews.js

Reviewroutes

---

frontend/src/App.js
frontend/src/components/EditUserInfo/EditUserInfoModal.js
frontend/src/components/NavBar/NavBar.css
frontend/src/components/NavBar/NavBar.js
frontend/src/components/Profile/Profile.js
frontend/src/components/Profile/Profile.scss
frontend/src/components/SessionForms/SessionForm.scss
frontend/src/components/SplashPage/SplashPage.scss
frontend/src/components/UserInfo/Avatar.js
frontend/src/components/UserInfo/UserInfo.js
frontend/src/components/UserInfo/UserInfo.scss

- Stylize profile layout
- Add posts/reviews tabs to profiles
- Minor styling on splash page

Style profiles

---

backend/seeders/images.js
frontend/package-lock.json
frontend/package.json

implemented aws, posts can upload pictures now

implemented aws, posts can upload pictures now

---

frontend/src/components/NavBar/CategoryNav.js
frontend/src/components/NavBar/NavBar.js
frontend/src/components/NavBar/NavBar.scss
frontend/src/store/categories.js
frontend/src/store/store.js

- create CategoryNav
- add categoryNav to NavBar
- create categories reducer
- add categories reducer to store

create category reducer, create category navbar

---

backend/awsS3.js
backend/config/passport.js
backend/models/Category.js
backend/models/Game.js
backend/models/Post.js
backend/models/User.js
backend/package-lock.json
backend/package.json
backend/routes/api/games.js
backend/routes/api/posts.js
backend/routes/api/users.js
backend/seeders/images.js
backend/seeders/seeds.js

added videos to posts

---

frontend/src/App.js
frontend/src/App.scss
frontend/src/components/CategoryDropdown/CategoryDropdown.js
frontend/src/components/CategoryDropdown/CategoryDropdown.scss
frontend/src/components/NavBar/CategoryNav.js
frontend/src/components/NavBar/NavBar.scss

- new page layout with side bar and main content
- style side bar

rearrange app.js layout and set up navbar

---

backend/routes/api/games.js
backend/seeders/seeds.js
frontend/src/App.js
frontend/src/components/GameShow/GameShow.js
frontend/src/components/GameShow/GameShow.scss
frontend/src/store/games.js
frontend/src/store/store.js

game show page

---

backend/models/Comment.js
backend/models/Game.js
backend/models/Post.js
backend/routes/api/games.js
backend/seeders/seeds.js
frontend/.env
frontend/config-overrides.js
frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/components/GameShow/GameShow.js
frontend/src/store/games.js
frontend/src/store/posts.js

fixed all the errors kind of

---

backend/routes/api/games.js
backend/seeders/seeds.js
frontend/src/App.js
frontend/src/components/GameShow/GameShow.js
frontend/src/store/games.js

finished gameshow

---

backend/models/Post.js
backend/models/User.js
backend/routes/api/posts.js

updated/created postCustomRoutes
Still need to change the reducer and create thunk action creators

Post custom routes

---

backend/routes/api/users.js
frontend/package.json
frontend/src/components/NavBar/NavBar.js
frontend/src/components/NavBar/NavBar.scss
frontend/src/components/UserInfo/Avatar.js

- also added profileImageUrl to info sent back for /:username route

fix user profile

---

backend/app.js
backend/models/Comment.js
backend/routes/api/comments.js
backend/routes/api/posts.js
backend/routes/api/users.js
backend/seeders/seeds.js

fixed it so that the hashedpassword doesnt show

fixed it so that the hashedpassword doesnt show

---

frontend/src/components/GameShow/GameShow.js
frontend/src/components/Profile/Profile.js
frontend/src/store/posts.js

Added custom thunk actions and then imported proper fetch requests for Gameshow and profile.
The useEffects should be dispatched the new thunk actions

finish postCustomThunkActions

---

backend/models/Comment.js
backend/models/Post.js
backend/routes/api/comments.js
backend/seeders/seeds.js

seeded comments

---

frontend/src/components/PostIndex/PostIndex.js
frontend/src/components/PostIndex/PostIndexItem.js

Refactor PostIndex to have PostIndexItems

Refactor PostIndex to have PostIndexItems

---

frontend/src/store/comments.js
frontend/src/store/errors.js
frontend/src/store/posts.js
frontend/src/store/reviews.js

adjusted all reducers because some of them had wrong variables names and weren't being passed into the errors slice of state.

Comments reducer

---

backend/seeders/seeds.js

seeded random profile images

---

frontend/src/store/reviews.js

fixed errors for reviews

---

frontend/src/App.scss
frontend/src/components/CategoryDropdown/CategoryDropdown.js
frontend/src/components/CategoryDropdown/CategoryDropdown.scss
frontend/src/components/GameShow/GameShow.scss
frontend/src/components/NavBar/CategoryNav.js
frontend/src/components/NavBar/NavBar.js
frontend/src/components/NavBar/NavBar.scss

i give up sorry, but please merge this for style fixes

Secondnavfix

---

backend/routes/api/posts.js
frontend/src/components/GameShow/GameShow.js
frontend/src/components/Profile/Profile.js
frontend/src/store/games.js

got rid of console logs from gameShow
Made final changes to posts slice of state

got rid of console logs and some minor changes

---

frontend/src/App.js
frontend/src/App.scss
frontend/src/components/NavBar/NavBar.js
frontend/src/components/NavBar/NavBar.scss
frontend/src/components/SplashPage/SplashPage.js
frontend/src/components/SplashPage/SplashPage.scss

added about button

---

backend/models/Post.js

fixed more errors

---

frontend/src/components/AboutPage/AboutPage.scss
frontend/src/components/NavBar/NavBar.js
frontend/src/components/NavBar/NavBar.scss
frontend/src/components/SplashPage/SplashPage.js

fixed the meet the team button when logged in and out

fixed the meet the team button when logged in and out

---

frontend/src/components/PostIndex/PostIndex.scss
frontend/src/components/ReviewIndex/ReviewIndex.scss
frontend/src/components/ReviewIndex/ReviewIndexItem.js

Reviews index

---

frontend/src/components/CommentsIndex/CommentsIndex.js
frontend/src/components/CommentsIndex/CommentsIndex.scss
frontend/src/store/comments.js

add send button and change styling on comments

Change styling on comments and add Send button

---

backend/seeders/seeds.js
frontend/src/App.scss
frontend/src/components/GameShow/GameShow.js
frontend/src/components/GameShow/GameShow.scss
frontend/src/components/HomePage/HomePage.js
frontend/src/components/HomePage/HomePage.scss
frontend/src/components/Swiper/pagination.scss
frontend/src/components/Swiper/swiper.scss

added slider to gamepage and started homepage

added slider to gamepage and started homepage

---

frontend/src/components/AboutPage/AboutPage.scss
frontend/src/components/GameShow/GameShow.scss
frontend/src/components/HomePage/HomePage.js
frontend/src/components/HomePage/HomePage.scss

fixed homepage and about button

fixed homepage and about button

---

backend/app.js

-changed order of where the isProduction clause is for render to be after app.use(csurf)

changed backend app.js

---

backend/seeders/seeds.js

added substring limits in seed files

fixed description validations in seeds

---

frontend/src/components/PostIndex/PostIndexItem.js

fix posts to only be able to be edited and deleted if the user is the author

---

frontend/src/components/PostIndex/PostIndexItem.js
frontend/src/components/ReviewForms/UpdateReviewModal.js
frontend/src/components/ReviewIndex/ReviewButtons.js
frontend/src/components/ReviewIndex/ReviewIndex.scss
frontend/src/components/ReviewIndex/ReviewIndexItem.js
frontend/src/store/reviews.js

implemented delete functionality for reviews

Reviews delete

---

backend/seeders/seeds.js
frontend/public/index.html
frontend/public/manifest.json

added a link tag to index.html
changed start_url in manifest.json

made changes from stackoverflow

---

frontend/public/index.html

changed manifest href line

---

frontend/.env
frontend/public/index.html
frontend/public/manifest.json

env was making public url to go to a relative path
it was ./

corrected env in front end and also adjusted index.html

---

frontend/src/components/EditUserInfo/EditUserInfoForm.js
frontend/src/components/UserInfo/UserInfo.js

display the right image on user profile
rerender user profile on edit user info
update users slice of state after edit as well

fix rerendering of user profile

---

frontend/src/App.scss
frontend/src/components/CommentsIndex/CommentsIndexItem.js
frontend/src/components/PostForms/CreatePostForm.js
frontend/src/components/PostForms/UpdatePostForm.js
frontend/src/components/ReviewForms/CreateReviewForm.js
frontend/src/components/ReviewForms/Rating.js
frontend/src/components/ReviewForms/ReviewForms.scss
frontend/src/components/ReviewForms/UpdateReviewForm.js
frontend/src/components/ReviewIndex/ReviewIndex.js
frontend/src/components/ReviewIndex/ReviewIndex.scss
frontend/src/components/ReviewIndex/ReviewIndexItem.js
frontend/src/components/SessionForms/SessionForm.scss

post:
- error messages
- fix delete confirmation
reviews:
- fix review being able review yourself
- only allow 1 - 5 star ratings
- buttons stay
- error messages + handling

Error handling

---

backend/routes/api/comments.js
frontend/src/components/CommentsIndex/CommentsIndex.js
frontend/src/components/CommentsIndex/CommentsIndex.scss
frontend/src/components/CommentsIndex/CommentsIndexItem.js
frontend/src/components/UserInfo/Avatar.js

- Fix comments bug: now properly displays author's PFP/username
- Add styling to comments
- Fix comments bug: currently logged user can only edit their own authored comments

Commentsupdatefix

---

backend/routes/api/reviews.js

created backend route for average rating

created backend route for average rating

---

backend/routes/api/games.js
frontend/src/App.js
frontend/src/components/GameShow/GameShow.js
frontend/src/components/LostPage/LostPage.js
frontend/src/components/LostPage/LostPage.scss
frontend/src/components/NavBar/NavBar.js
frontend/src/components/NavBar/NavBar.scss
frontend/src/components/Profile/Profile.js
frontend/src/store/errors.js
frontend/src/store/games.js
frontend/src/store/jwt.js
frontend/src/store/users.js

reroutes to the 404 error page whenever a user tries to enter a url to a user/game that doesn't exist
- I also fixed some error handling on the backend

Notfoundpage

---

backend/models/Comment.js
backend/models/Post.js
backend/seeders/seeds.js
frontend/src/components/PostIndex/PostIndexItem.js

Averagerating

---

backend/routes/api/users.js
frontend/src/components/EditUserInfo/EditUserInfoForm.js
frontend/src/components/GameShow/GameShow.js
frontend/src/components/PostForms/CreatePostForm.js
frontend/src/components/PostForms/UpdatePostForm.js
frontend/src/components/ReviewForms/CreateReviewForm.js
frontend/src/components/ReviewForms/UpdateReviewForm.js
frontend/src/components/ReviewIndex/ReviewButtons.js
frontend/src/components/ReviewIndex/ReviewIndexItem.js
frontend/src/components/UserInfo/UserInfo.js
frontend/src/store/jwt.js
frontend/src/store/posts.js
frontend/src/store/session.js
frontend/src/store/users.js

- allow for image upload on edit user form
- allow for editing posts on user profile
- changed lots of files, srry

Profile upload

---

frontend/src/components/CategoryDropdown/CategoryDropdown.scss
frontend/src/components/EditUserInfo/EditUserInfoForm.js
frontend/src/components/GameShow/GameShow.js
frontend/src/components/ReviewForms/CreateReviewForm.js
frontend/src/components/ReviewForms/ReviewForms.scss
frontend/src/components/SessionForms/SessionForm.scss
frontend/src/components/UserInfo/UserInfo.scss

- Add minor styling to navbar and various buttons

Add minor styling to navbar and various buttons

---

frontend/src/components/PostIndex/PostIndexItem.js
frontend/src/components/Profile/Profile.js
frontend/src/components/UserInfo/Avatar.js

- rerender posts when profileImageUrl changes in post tab
- onclick scroll to top for avatar

rerender profile image in post tab + scroll to top on avatars

---

frontend/src/components/EditUserInfo/EditUserInfoForm.js
frontend/src/components/SessionForms/LoginForm.js
frontend/src/components/SessionForms/SessionForm.scss
frontend/src/components/SessionForms/SignupForm.js

- add profile pic preview to edit user profile form
- add demo login button to sign up form

Pfppreview

---

frontend/src/components/ReviewForms/CreateReviewModal.js
frontend/src/components/ReviewIndex/ReviewIndex.js
frontend/src/components/UserInfo/UserInfo.js
frontend/src/context/modal.css

- move review button to user info component
- add z-index to modal

Reviewbutton

---

frontend/src/components/AuthCards/AuthCards.scss
frontend/src/components/Posts/PostButtons.jsx
frontend/src/components/Posts/PostIndex.jsx
frontend/src/components/Posts/PostIndex.scss
frontend/src/components/Posts/PostIndexItem.jsx
frontend/src/components/Posts/TimeStamp.jsx
frontend/src/components/Posts/UpdatePostButton.jsx
frontend/src/components/Posts/UpdatePostForm.jsx
frontend/src/components/Profile/EditProfile.jsx
frontend/src/components/Profile/EditProfile.scss
frontend/src/components/Profile/Profile.scss
frontend/src/components/Profile/RevPostCard/RevPostCard.jsx
frontend/src/components/Profile/RevPostCard/RevPostCard.scss
frontend/src/components/Profile/ReviewForm.scss

- Create Posts/Reviews Card for User Profile
- Create Post Index and associated (unfinished) components (PostIndexItem, PostButtons, etc.)

Redesign profile - Posts

---

frontend/src/App.scss
frontend/src/components/AuthNavBar/CategoryNav.js
frontend/src/components/Comments/CommentIndex.jsx
frontend/src/components/Comments/CommentIndex.scss
frontend/src/components/Comments/CommentIndexItem.jsx
frontend/src/components/Posts/PostButtons.jsx
frontend/src/components/Posts/PostIndex.scss
frontend/src/components/Posts/PostIndexItem.jsx
frontend/src/components/Posts/UpdatePostForm.jsx
frontend/src/components/Posts/UpdatePostForm.scss
frontend/src/components/Profile/Profile.scss
frontend/src/components/Profile/RevPostCard/RevPostCard.scss
frontend/src/components/Profile/Summary.jsx
frontend/src/components/Profile/UserCard.jsx

- Add Comment Index
- Change highlight yellow to highlight orange

Redesign profile - Comment Index

---

backend/seeders/seeds.js
frontend/src/App.js
frontend/src/components/AuthCards/AuthCards.scss
frontend/src/components/Comments/CommentIndex.jsx
frontend/src/components/Comments/CommentIndex.scss
frontend/src/components/GameShow/GameCard.jsx
frontend/src/components/GameShow/GameCard.scss
frontend/src/components/GameShow/GameShow.jsx
frontend/src/components/Posts/PostIndex.jsx
frontend/src/components/Posts/PostIndex.scss
frontend/src/components/Profile/EditProfile.jsx
frontend/src/components/Profile/EditProfile.scss
frontend/src/components/Profile/Profile.scss
frontend/src/components/Reviews/ReviewForm.scss
frontend/src/context/modal.css

- Create Game Show Page
- Create form to create a Post
- Handle posts fade-out styling in Game Show Post Index

Redesign game show
